### PR TITLE
Fix Subscribe

### LINKED ISSUE #95: Test gNMI subscribe on the Southbound
The gNMI subscription on the southbound needs testing and possibile refactoring

### PR DESCRIPTION
**Pull request by Andrea-Campanella**
Moving CacheClient to BaseClient to allow swap of ProtoHandler.
Protohandler implementation allows us to intercept and parse the message at the level we need.

Allows for subscription notifications to be upstreamed to gnmi_cli. 

Fixes #95

### CODE REVIEW

File: pkg/southbound/synchronizer/synchronizer.go [hunk 1]
```diff
@@ -122,38 +123,58 @@ func (sync Synchronizer) syncOperationalState() error {
...
+		//Stratum
+		//path = append(path, "interfaces")
+		//path = append(path, "interface[name=s1-eth1]")
+		////path = append(path, "state")
+		////path = append(path, "admin-status")
+		//path = append(path, "config")
+		//path = append(path, "enabled")
+
+		//Simulator
+		path = append(path, "system")
```
Comment (SeanCondon) [inline pkg/southbound/synchronizer/synchronizer.go]: Deserves a big FIXME

**Comment by Andrea-Campanella** [comment]
With this last commit it returns an error if no paths. Commented out the hardcoded stuff but left there FYI until we get the path getting out of models done. 
If you guys are ok we can merge.
