### PR TITLE
Fixed handling of extension 101 and 102 Fixes #636

### LINKED ISSUE #636: Error when creating a new config using gNMI NBI using extensions 101 and 102
**Describe the bug**
It should be possible to create a new config (without any attached device) using extensions 101 and 102. 

**To Reproduce**
```
gnmi_cli -address onos-config:5150 -set \
-proto "update: <path: <target: 'devicesim2', elem: <name: 'system'> elem: <name: 'clock' > elem: <name: 'config'> elem: <name: 'timezone-name'>> val: <string_val: 'Europe/Paris'>> extension: <registered_ext: <id: 101, msg:'2.0.0'>> extension: <registered_ext: <id: 102, msg:'Devicesim'>>" \
-timeout 5s -alsologtostderr -client_crt /etc/onos -config/certs/client1.crt -client_key /etc/onos-config/certs/client1.key -ca_crt
 /etc/onos-config/certs/onf.cacrt
```
This gives the error
```
E0815 08:26:58.443344      94 gnmi_cli.go:180] target returned RPC error for Set("update:<path:<elem:<name:\"system\" > elem:<name:\"clock\" > elem:<name:\"config\" > elem:<name:\"timezone-name\" > target:\"devicesim2\" > val:<string_val:\"Europe/Paris\" > > extension:<registered_ext:<id:101 msg:\"2.0.0\" > > extension:<registered_ext:<id:102 msg:\"Devicesim\" > > ") : rpc error: code = Unknown desc = no configuration found matching 'devicesim2-2.0.0'.Please specify version and device type in extensions 101 and 102
```

**Expected behavior**
It should give a result like:
```
response: <
  path: <
    elem: <
      name: "system"
    >
    elem: <
      name: "clock"
    >
    elem: <
      name: "config"
    >
    elem: <
      name: "timezone-name"
    >
    target: "devicesim2"
  >
  op: UPDATE
>
timestamp: 1565857653
extension: <
  registered_ext: <
    id: 100
    msg: "amazing_williams"
  >
>
```

**Additional context**
This needs to be fixed in **setconfig.go** line 145

### PR DESCRIPTION
**Pull request by SeanCondon**
Also added in the generation of comments when creating changes

### CODE REVIEW

File: pkg/manager/setconfig.go [hunk 1]
```diff
@@ -29,25 +29,20 @@ const SetConfigAlreadyApplied = "Already applied:"
...
 	if err != nil {
 		return err
 	}
 	deviceConfigTemporary, _ := store.CreateConfiguration(deviceConfig.Device, deviceConfig.Version,
 		deviceConfig.Type, deviceConfig.Changes)
-	chg, err := m.computeChange(updates, deletes)
-	if err != nil {
-		return err
-	}
-	changeID, err := m.storeChange(chg)
```
Comment (SeanCondon) [inline pkg/manager/setconfig.go]: We were storing the change here - should not have been because it might have been invalid. Now I'm saving it after it's been validated in SetNetworkConfig
